{% set version = "4.2.4" %}

package:
  name: omniorb
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/omniorb/files/omniORB/omniORB-{{ version }}/omniORB-{{ version }}.tar.bz2
  sha256: 28c01cd0df76c1e81524ca369dc9e6e75f57dc70f30688c99c67926e4bdc7a6f
  patches:
    - patch-configure.diff
    - 0001-Avoid-kernel-128-character-shebang-limit.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - make
  host:
    - python
    - openssl
    - zlib
  run:
    - python
    - zlib

test:
  source_files:
    - idl/echo.idl
  commands:
    - omniidl -bcxx idl/echo.idl

about:
  home: http://omniorb.sourceforge.net/index.html
  license: GPL-2.0
  license_file: COPYING
  summary: Robust high performance CORBA ORB for C++ and Python

  description: |
    omniORB is an Object Request Broker (ORB) which implements
    specification 2.6 of the Common Object Request Broker Architecture
    (CORBA).
  doc_url: http://omniorb.sourceforge.net/docs.html
  dev_url: https://sourceforge.net/projects/omniorb/

extra:
  recipe-maintainers:
    - carlodri
    - lockhart
