{% set version = "4.3.2" %}

package:
  name: omniorb-suite
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/omniorb/files/omniORB/omniORB-{{ version }}/omniORB-{{ version }}.tar.bz2
    sha256: 1c745330d01904afd7a1ed0a5896b9a6e53ac1a4b864a48503b93c7eecbf1fa8
    patches:
      - 0001-Avoid-kernel-128-character-shebang-limit.patch  # [unix]
      - find-openssl-root.patch                              # [unix]
      - windows-build.patch                                  # [win]
      - fix-macos-compatibility-version.patch                # [osx]
  - url: https://sourceforge.net/projects/omniorb/files/omniORBpy/omniORBpy-{{ version }}/omniORBpy-{{ version }}.tar.bz2
    sha256: cb5717d412a101baf430f598cac7d69231884dae4372d8e2adf3ddeebc5f7ebb
    patches:
      - windows-build-omniorbpy.patch                        # [win]
      - find-openssl-root-omniorbpy.patch                    # [unix]
    folder: src/lib/omniORBpy

build:
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - zstd                                   # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf    # [unix]
    - pkg-config  # [unix]
    - make
    - posix     # [win]
  host:
    - python
    - openssl
    - zlib
    - zstd


outputs:
  - name: omniorb-libs
    script: install_omniorb.sh   # [unix]
    script: install_omniorb.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('omniorb-libs', max_pin='x.x') }}
      ignore_run_exports_from:
        - python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - zstd                                   # [build_platform != target_platform]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
      host:
        - openssl
        - zlib
        - zstd
    test:
      commands:
        - test -f ${PREFIX}/include/omniconfig.h                           # [unix]
        - test -f ${PREFIX}/include/omnithread.h                           # [unix]
        - test -f ${PREFIX}/include/omniORB4/acconfig.h                    # [unix]
        - test -f ${PREFIX}/lib/libomniORB4${SHLIB_EXT}                    # [unix]
        - test -f ${PREFIX}/lib/libCOS4${SHLIB_EXT}                        # [unix]
        - test -f ${PREFIX}/lib/libomnisslTP4${SHLIB_EXT}                  # [unix]
        - test -f ${PREFIX}/lib/libomnithread${SHLIB_EXT}                  # [unix]
        - test -f ${PREFIX}/lib/pkgconfig/omniORB4.pc                      # [unix]
        - if not exist %LIBRARY_INC%\\omniconfig.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\\omnithread.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\\omniORB4\\CORBA.h exit 1             # [win]
        - if not exist %LIBRARY_BIN%\\omniORB4_rt.dll exit 1               # [win]
        - if not exist %LIBRARY_BIN%\\COS4_rt.dll exit 1                   # [win]
        - if not exist %LIBRARY_BIN%\\omnisslTP4_rt.dll exit 1             # [win]
        - if not exist %LIBRARY_BIN%\\omnithread_rt.dll exit 1             # [win]
        - if not exist %LIBRARY_LIB%\\omniORB4_rt.lib exit 1               # [win]
        - if not exist %LIBRARY_LIB%\\COS4_rt.lib exit 1                   # [win]
        - if not exist %LIBRARY_LIB%\\omnisslTP4_rt.lib exit 1             # [win]
        - if not exist %LIBRARY_LIB%\\omnithread_rt.lib exit 1             # [win]

  - name: omniorb
    script: install_omniorb.sh   # [unix]
    script: install_omniorb.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('omniorb-libs', max_pin='x.x') }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - zstd                                   # [build_platform != target_platform]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
      host:
        - python
        - openssl
        - zlib
        - zstd
        - {{ pin_subpackage('omniorb-libs', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('omniorb-libs', exact=True) }}
    test:
      source_files:
        - idl/echo.idl
      commands:
        - omniidl -bcxx idl/echo.idl                         # [unix]
        - test -f $PREFIX/bin/catior                         # [unix]
        - test -f $PREFIX/bin/convertior                     # [unix]
        - test -f $PREFIX/bin/genior                         # [unix]
        - test -f $PREFIX/bin/nameclt                        # [unix]
        - test -f $PREFIX/bin/omkdepend                      # [unix]
        - test -f $PREFIX/bin/omniidl                        # [unix]
        - if not exist %LIBRARY_BIN%\\catior.exe exit 1      # [win]
        - if not exist %LIBRARY_BIN%\\convertior.exe exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\genior.exe exit 1      # [win]
        - if not exist %LIBRARY_BIN%\\nameclt.exe exit 1     # [win]
        - if not exist %LIBRARY_BIN%\\omkdepend.exe exit 1   # [win]
        - if not exist %LIBRARY_BIN%\\omniidl.exe exit 1     # [win]

  - name: omniorbpy
    script: install_omniorbpy.sh   # [unix]
    script: install_omniorbpy.bat  # [win]
    requirements:
      build:
        - python                                       # [build_platform != target_platform]
        - cross-python_{{ target_platform }}           # [build_platform != target_platform]
        - gnuconfig  # [unix]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - autoconf   # [unix]
        - make
        - posix      # [win]
      host:
        - python
        - openssl
        - {{ pin_subpackage('omniorb', exact=True) }}
        - {{ pin_subpackage('omniorb-libs', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('omniorb', exact=True) }}
        - {{ pin_subpackage('omniorb-libs', exact=True) }}
    test:
      source_files:
        - src/lib/omniORBpy/examples/echo/example_echo.idl
      commands:
        - omniidl -v -bpython src/lib/omniORBpy/examples/echo/example_echo.idl

about:
  home: http://omniorb.sourceforge.net/index.html
  license: GPL-2.0-or-later OR LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LIB
  summary: Robust high performance CORBA ORB for C++ and Python
  description: |
    omniORB is an Object Request Broker (ORB) which implements
    specification 2.6 of the Common Object Request Broker Architecture
    (CORBA).
  doc_url: http://omniorb.sourceforge.net/docs.html
  dev_url: https://sourceforge.net/projects/omniorb/

extra:
  feedstock-name: omniorb
  recipe-maintainers:
    - beenje
    - carlodri
    - lockhart
