{% set version = "4.3.1" %}

package:
  name: omniorb
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/omniorb/files/omniORB/omniORB-{{ version }}/omniORB-{{ version }}.tar.bz2
  sha256: 0f42bc3eb737cae680dafa85b3ae3958e9f56a37912c5fb6b875933f8fb7390d
  patches:
    - 0001-Avoid-kernel-128-character-shebang-limit.patch  # [unix]
    - windows-build.patch                                  # [win]
    - patch-configure.diff                                 # [unix]

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - zstd                                   # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - make
    - posix     # [win]
  host:
    - python
    - openssl
    - zlib
    - zstd
  run:
    - python
    - {{ pin_subpackage('omniorb-libs', exact=True) }}

test:
  source_files:
    - idl/echo.idl
  commands:
    - omniidl -bcxx idl/echo.idl  # [unix]

outputs:
  - name: omniorb-libs
    build:
      run_exports:
        - {{ pin_subpackage('omniorb-libs', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - autoconf  # [unix]
        - make
        - posix     # [win]
      host:
        - openssl
        - zlib
        - zstd
    files:
      - include/COS                  # [unix]
      - include/omniORB4             # [unix]
      - include/omnithread           # [unix]
      - include/omni*                # [unix]
      - lib/pkgconfig/omni*.pc       # [unix]
      - Library/include/COS          # [win]
      - Library/include/omniORB4     # [win]
      - Library/include/omnithread   # [win]
      - Library/include/omniVms      # [win]
      - Library/include/omni*        # [win]
      - lib/libomni*.so*             # [linux]
      - lib/libCOS*.so*              # [linux]
      - lib/libomni*.dylib           # [osx]
      - lib/libCOS*.dylib            # [osx]
      - Library/bin/COS*_rt.dll      # [win]
      - Library/bin/omni*_rt.dll     # [win]
      - Library/lib/COS*_rt.lib      # [win]
      - Library/lib/omni*_rt.lib     # [win]
    test:
      commands:
        - test -f ${PREFIX}/include/omniconfig.h                           # [unix]
        - test -f ${PREFIX}/include/omnithread.h                           # [unix]
        - test -f ${PREFIX}/include/omniORB4/acconfig.h                    # [unix]
        - test -f ${PREFIX}/lib/libomniORB4${SHLIB_EXT}                    # [unix]
        - test -f ${PREFIX}/lib/libCOS4${SHLIB_EXT}                        # [unix]
        - test -f ${PREFIX}/lib/libomnithread${SHLIB_EXT}                  # [unix]
        - test -f ${PREFIX}/lib/pkgconfig/omniORB4.pc                      # [unix]
        - if not exist %LIBRARY_INC%\\omniconfig.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\\omnithread.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\\omniORB4\\CORBA.h exit 1             # [win]
        - if not exist %LIBRARY_BIN%\\omniORB4_rt.dll exit 1               # [win]
        - if not exist %LIBRARY_BIN%\\COS4_rt.dll exit 1                   # [win]
        - if not exist %LIBRARY_BIN%\\omnithread_rt.dll exit 1             # [win]
        - if not exist %LIBRARY_LIB%\\omniORB4_rt.lib exit 1               # [win]
        - if not exist %LIBRARY_LIB%\\COS4_rt.lib exit 1                   # [win]
        - if not exist %LIBRARY_LIB%\\omnithread_rt.lib exit 1             # [win]
  - name: omniorb
    files:
      # WARNING! globs aren't supported for directories (only files)
      # conda-build will NOT filter on new files only!
      - bin/catior                                       # [unix]
      - bin/convertior                                   # [unix]
      - bin/genior                                       # [unix]
      - bin/nameclt                                      # [unix]
      - bin/omkdepend                                    # [unix]
      - bin/omni*                                        # [unix]
      - etc/omniORB-config                               # [unix]
      - lib/libomni*.a                                   # [unix]
      - lib/libCOS*.a                                    # [unix]
      - lib/python{{ PY_VER }}/site-packages/_omniidl*   # [unix]
      - lib/python{{ PY_VER }}/site-packages/omniidl     # [unix]
      - lib/python{{ PY_VER }}/site-packages/omniidl_be  # [unix]
      - share/idl/omniORB                                # [unix]
      - var/omniNames-logs                               # [unix]
      - Library/bin/catior.exe                           # [win]
      - Library/bin/convertior.exe                       # [win]
      - Library/bin/genior.exe                           # [win]
      - Library/bin/nameclt.exe                          # [win]
      - Library/bin/omkdepend.exe                        # [win]
      - Library/bin/omni*.exe                            # [win]
      - Lib/site-packages/omniidl                        # [win]
      - Lib/site-packages/omniidl_be                     # [win]

about:
  home: http://omniorb.sourceforge.net/index.html
  license: GPL-2.0-or-later OR LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LIB
  summary: Robust high performance CORBA ORB for C++ and Python
  description: |
    omniORB is an Object Request Broker (ORB) which implements
    specification 2.6 of the Common Object Request Broker Architecture
    (CORBA).
  doc_url: http://omniorb.sourceforge.net/docs.html
  dev_url: https://sourceforge.net/projects/omniorb/

extra:
  recipe-maintainers:
    - beenje
    - carlodri
    - lockhart
