{% set version = "4.2.5" %}

package:
  name: omniorb
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/omniorb/files/omniORB/omniORB-{{ version }}/omniORB-{{ version }}.tar.bz2
  sha256: f05cf999fb2f4c24c1173b3c44ad97215591d0d1a48d49ac0843c464efe073bb
  patches:
    - patch-configure.diff
    - 0001-Avoid-kernel-128-character-shebang-limit.patch
    - 0002-Update-config-guess.patch
    - omniorb-4.2.5-cmake.patch  # [win]

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - make      # [unix]
    - cmake >=3.12  # [win]
  host:
    - python
    - openssl
    - zlib

test:
  source_files:
    - idl/echo.idl
  commands:
    - omniidl -bcxx idl/echo.idl  # [unix]

outputs:
  - name: omniorb-libs
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - autoconf  # [unix]
        - make      # [unix]
        - cmake >=3.12  # [win]
      host:
        - openssl
        - zlib
    files:
      - include                      # [unix]
      - Library/include              # [win]
      - lib/libomni*.so*             # [linux]
      - lib/libCOS*.so*              # [linux]
      - lib/libomni*.dylib           # [osx]
      - lib/libCOS*.dylib            # [osx]
      - Library/bin/COS*.dll         # [win]
      - Library/bin/omni*.dll        # [win]
      - Library/lib/COS*.lib         # [win]
      - Library/lib/omni*.lib        # [win]
    test:
      commands:
        - test -f ${PREFIX}/include/omniconfig.h                           # [unix]
        - test -f ${PREFIX}/include/omnithread.h                           # [unix]
        - test -f ${PREFIX}/include/omniORB4/acconfig.h                    # [unix]
        - test -f ${PREFIX}/lib/libomniORB4${SHLIB_EXT}                    # [unix]
        - test -f ${PREFIX}/lib/libCOS4${SHLIB_EXT}                        # [unix]
        - test -f ${PREFIX}/lib/libomnithread${SHLIB_EXT}                  # [unix]
        - if not exist %LIBRARY_INC%\\omniconfig.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\\omnithread.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\\omniORB4\\acconfig.h exit 1          # [win]
        - if not exist %LIBRARY_BIN%\\omniORB4_rt.dll exit 1               # [win]
        - if not exist %LIBRARY_BIN%\\COS4_rt.dll exit 1                   # [win]
        - if not exist %LIBRARY_BIN%\\omnithread_rt.dll exit 1             # [win]
        - if not exist %LIBRARY_LIB%\\omniORB4_rt.lib exit 1               # [win]
        - if not exist %LIBRARY_LIB%\\COS4_rt.lib exit 1                   # [win]
        - if not exist %LIBRARY_LIB%\\omnithread_rt.lib exit 1             # [win]
  - name: omniorb
    build:
      run_exports:
        - {{ pin_subpackage('omniorb-libs', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - autoconf  # [unix]
        - make      # [unix]
        - cmake >=3.12  # [win]
      host:
        - python
        - openssl
        - zlib
      run:
        - python
        - {{ pin_subpackage('omniorb-libs', exact=True) }}
    files:
      # WARNING! globs aren't supported for directories (only files)
      # Let conda-build only include new files from each directory
      - bin                                   # [unix]
      - etc                                   # [unix]
      - lib/pkgconfig                         # [unix]
      - lib/libomni*.a                        # [unix]
      - lib/libCOS*.a                         # [unix]
      - lib/python{{ PY_VER }}/site-packages  # [unix]
      - share/idl/omniORB                     # [unix]
      - var/omniNames-logs                    # [unix]
      - Library/bin/*.exe                     # [win]
      - Library/lib/cmake/OmniORB             # [win]
      - Lib/site-packages                     # [win]

about:
  home: http://omniorb.sourceforge.net/index.html
  license: GPL-2.0-or-later OR LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LIB
  summary: Robust high performance CORBA ORB for C++ and Python
  description: |
    omniORB is an Object Request Broker (ORB) which implements
    specification 2.6 of the Common Object Request Broker Architecture
    (CORBA).
  doc_url: http://omniorb.sourceforge.net/docs.html
  dev_url: https://sourceforge.net/projects/omniorb/

extra:
  recipe-maintainers:
    - beenje
    - carlodri
    - lockhart
